robotpincher:
joint_state_controller:
type: joint_state_controller/JointStateController
Publish_rate: 50

joint1_position_controller:
type: effort_controllers/JointPositionController
joint: Joint1
pid: {p: 1.0, i: 0.0, d: 0.0}

joint2_position_controller:
type: effort_controllers/JointPositionController
joint: Joint2
pid: {p: 1.0, i: 0.0, d: 0.0}

joint3_position_controller:
type: effort_controllers/JointPositionController
joint: Joint3
pid: {p: 1.0, i: 0.0, d: 0.0}

joint4_position_controller:
type: effort_controllers/JointPositionController
joint: Joint4
pid: {p: 1.0, i: 0.0, d: 1.0}
